export const LAYER = {
  ADD: 'LAYER_ADD',
  REMOVE: 'LAYER_REMOVE',
  GET_INFO:'LAYER_GET_INFO',
  MOVE_LAYER:'LAYER_MOVE_LAYER',
  CLEAR_DRAG:'LAYER_CLEAR_DRAG'
};

export const MAP = {
  GET_CONFIG: 'MAP_GET_CONFIG',
  GET_PROJECTION: 'MAP_GET_PROJECTION',
  SET_LAT_LON: 'MAP_SET_LAT_LON',
  LON_LAT_TO_CENTER: 'MAP_LON_LAT_TO_CENTER',
  SET_VIEW: 'MAP_SET_VIEW'
};
